### ISSUE TITLE
Clean up RenderType

### ISSUE THREAD

**Issue by pforhan** [pforhan/wannabe#3]
Clarify the relationship with Projection.  Break the link with Swing

**Comment by psh** [comment]
I'd be happy to break RenderType apart - looks like there might be a `Renderer` interface in there somewhere, along with some shared code.  The graphics operations could also be abstracted through an interface along with a concrete `SwingGraphics` implementation.  By the look of it, the iteration (using `next()`) is more about being able to step through things in your Swing UI so there really doesn't need to be an enum.

**Comment by pforhan** [comment]
You've hit the nail right on the head.

**Comment by pforhan** [comment]
I stopped short of making a swingGraphics interface, and in fact went and pushed it all into swing at this time.  when we get to a second 2d instance, like android, we can se what can be reused.
